# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master, next, alpha and beta branch
on:
  push:
    branches: [ master, next, alpha, beta ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Only release on push to master
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: npm install

    - name: Build
      run: npm run generate
      env:
        FSXA_API_KEY: ${{ secrets.API_KEY }}
        FSXA_CAAS: ${{ secrets.FSXA_CAAS }}
        FSXA_MODE: ${{ secrets.FSXA_MODE }}
        FSXA_NAVIGATION_SERVICE: ${{ secrets.FSXA_NAVIGATION_SERVICE }}
        FSXA_LOCALE: ${{ secrets.FSXA_LOCALE }}
        FSXA_TENANT_ID: ${{ secrets.FSXA_TENANT_ID }}
        FSXA_PROJECT_ID: ${{ secrets.FSXA_PROJECT_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
